### ISSUE TITLE
给ihub-boot加一些功能

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#15]
原`springboot_common_settings.gradle`中包含三个增强特性：

* 把传给Gradle task的`-D`参数，悉数传给应用进程
* 提供一个类似于`.env`的功能
  这个功能有两种实现思路
  * 参考`springboot_common_settings.gradle`
  * 引入[paulschwarz/spring-dotenv](https://github.com/paulschwarz/spring-dotenv)
* 支持运行时以exploded的形式跑app，并支持定制解包内容

**Comment by henry-hub** [comment]
会在**完善ihub-boot插件 #3**任务添加
