### ISSUE TITLE
ihub-test插件读取test.*属性有问题

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#21]
# **Describe the bug**
我指定了`-Dtest.maxParallelForks=1`，但是下图明显用上了所有核（16个）。
![image](https://user-images.githubusercontent.com/5813426/118158758-cc1f8a80-b44e-11eb-89e1-4fb62644aa4c.png)

# **To Reproduce**
最新 **cornucopia** ，`ihub-plugin`分支，执行下列命令行（小心CPU爆掉，直接飙到100%占用率，所以最好先本地把`testMaxParallelForks`改小点，如下图）：
`gradlew -Dspring.profiles.active=dev -Dspring.config.name=service,test -Ddebug=true -Dtest.maxParallelForks=1 -DjacocoPackageInstructionCoverageRuleEnabled=false -DjacocoBundleBranchCoveredRatio=0.2 -DjacocoBundleInstructionCoveredRatio=0.4 cleanTest test`
![image](https://user-images.githubusercontent.com/5813426/118160678-36d1c580-b451-11eb-9347-55f062ada379.png)

# **Expected behavior**
`-Dtest.maxParallelForks=1`意味着所有测试用例在一个进程里串行执行。

**Comment by henry-hub** [comment]
之前的扩展属性没有读取JVM环境属性，1.0.6已添加该特性
