### ISSUE TITLE
✨ ihub-git-hooks支持配置commit-msg模板

### ISSUE THREAD

**Issue by henry-hub** [ihub-pub/plugins#247]
### 检查清单

- [X] 我已阅读[支持文档](https://github.com/ihub-pub/.github/blob/main/SUPPORT.md)
- [X] 我已阅读[贡献指南](https://github.com/ihub-pub/.github/blob/main/CONTRIBUTING.md)
- [X] 我同意遵守[行为准则](https://github.com/ihub-pub/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 我查找了[issues](https://github.com/search?q=user%3Aihub-pub&type=Issues)但找不到任何相关内容（或在下面链接了相关结果）

### 问题

为`ihub-git-hooks`插件添加类似于[`commitlint`](https://www.npmjs.com/search?q=keywords:commitlint)的`commit-msg`检查能力

### 解决方案

- [x] 提供Gradle版本的`commitlint`任务用以`git commit`检查
- [x] 基于[约定式提交](https://www.conventionalcommits.org/)规范提供默认`commit-msg`检查模板
- [x] 支持基于基础模板的DSL个性化规则校验配置
- [x] 支持自动生成[`Conventional Commit`](https://plugins.jetbrains.com/plugin/13389-conventional-commit)IDEA插件配置文件`conventionalCommit.json`，[参见](https://github.com/lppedd/idea-conventional-commit)
- [x] 支持自动配置`conventionalCommit.xml`

**Comment by zhanghuabin** [comment]
能大致说说第3点的思路么？

我先说一下我的需求：

有点类似于如下`.commitlintrc.json`这个配置文件的目的——指定每个项目特有的规则。

```json
{
    "extends": [
        "@commitlint/config-conventional"
    ],
    "rules": {
        "scope-enum": [
            2,
            "always",
            [
                "rest",
                "service",
                "shared",
                "tests",
                "db",
                "redis",
                "cicd",
                "devops",
                "docker",
                "build",
                "conf",
                "javadoc",
                "doc"
            ]
        ]
    }
}
```

**Comment by henry-hub** [comment]
> 能大致说说第3点的思路么？
> 
> 我先说一下我的需求：
> 
> 有点类似于如下`.commitlintrc.json`这个配置文件的目的——指定每个项目特有的规则。
> 
> ```json
> {
>     "extends": [
>         "@commitlint/config-conventional"
>     ],
>     "rules": {
>         "scope-enum": [
>             2,
>             "always",
>             [
>                 "rest",
>                 "service",
>                 "shared",
>                 "tests",
>                 "db",
>                 "redis",
>                 "cicd",
>                 "devops",
>                 "docker",
>                 "build",
>                 "conf",
>                 "javadoc",
>                 "doc"
>             ]
>         ]
>     }
> }
> ```

- 支持添加自定义`type`及相关`scope`、`footerType`，根据这些配置信息会在项目下自动生成`conventionalcommit.json`配置，用于导入[`Conventional Commit`](https://plugins.jetbrains.com/plugin/13389-conventional-commit)插件
- 另外`footerType`支持`是否必填`校验配置，比如：`Reviewer`
- 后续也可以支持一些自定义正则，比如某种注脚需要什么样的格式

目前的`conventionalcommit.json`默认配置如下：
```json
{
  "types": {
    "refactor": {
      "description": "Changes which neither fix a bug nor add a feature"
    },
    "fix": {
      "description": "Changes which patch a bug"
    },
    "feat": {
      "description": "Changes which introduce a new feature"
    },
    "build": {
      "description": "Changes which affect the build system or external dependencies.<br/>Example scopes: gulp, broccoli, npm",
      "scopes": {
        "npm": {},
        "gulp": {},
        "broccoli": {}
      }
    },
    "chore": {
      "description": "Changes which aren't user-facing"
    },
    "style": {
      "description": "Changes which don't affect code logic, such as white-spaces, formatting, missing semi-colons"
    },
    "test": {
      "description": "Changes which add missing tests or correct existing tests"
    },
    "docs": {
      "description": "Changes which affect documentation"
    },
    "perf": {
      "description": "Changes which improve performance"
    },
    "ci": {
      "description": "Changes which affect CI configuration files and scripts.<br/>Example scopes: travis, circle, browser-stack, sauce-labs"
    },
    "revert": {
      "description": "Changes which revert a previous commit"
    }
  },
  "footerTypes": [
    {
      "name": "BREAKING CHANGE",
      "description": "The commit introduces breaking API changes"
    },
    {
      "name": "Closes",
      "description": "The commit closes issues or pull requests"
    },
    {
      "name": "Implements",
      "description": "The commit implements features"
    },
    {
      "name": "Co-authored-by",
      "description": "The commit is co-authored by another person.<br/>For multiple people use one line each"
    },
    {
      "name": "Refs",
      "description": "The commit references other commits by their hash ID.<br/>For multiple hash IDs use a comma as separator"
    }
  ]
}
```
