### ISSUE TITLE
可能.java-local.properties机制并不适合测试任务

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#28]
### Describe the bug
`.java-local.properties`机制貌似已经推广到了所有插件中，但是其在测试任务中的效果却貌似不是我们所期望的。

### To Reproduce
* cornucopia、ihub-plugin
* `verification_settings.gradle`，参考 #27
* 添加如下内容的`.java-local.properties`

```
debug=true
#server.port=22222
spring.boot.admin.client.url=http://192.168.8.104:8769
spring.boot.admin.client.username=cheche
spring.boot.admin.client.password=cheche365#
spring.config.name=rest,service
spring.datasource.username=cheche
spring.datasource.password=cheche
spring.datasource.url=jdbc:mysql://localhost:3306/sdas?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
cornucopia.profile.default.storage.type=_EXTERNAL_SERVICE

```

* 执行任务，参考 #27
* 报DB拒绝连接错

### Expected behavior
该项目功能测试无需连接写在`.java-local.properties`的MySQL，`spring.datasource.url`在本项目功能测试时不应生效。
至于改进方案，我也没想清楚，毕竟从 **Test** 插件中彻底移除`.java-local.properties`机制，好像也不是个好主意。
那么提供一个 **是否启用该机制的开关** 如何？由于所有插件都有该机制，但是不同插件默认是否开启该机制却有不同，比如 **Boot** 插件默认应该开启，而 **Test** 插件则正相反。

**Comment by henry-hub** [comment]
添加`.java-local.properties`属性启用开关`enabledLocalProperties`，`Boot`插件默认开启，`Test`插件默认关闭
