### ISSUE TITLE
请协助查看一下cornucopia使用最新版本插件时问题

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#319]
### 受影响的软件包和版本

1.2.10

### 可运行的示例链接

pub-apps/cornucopia:ihub-plugin-1.2.10

### 复现步骤

我在**cornucopia**的**ihub-plugin-1.2.10**分支里升级了插件版本。
按照 #299 里的说明改动了一些配置。

但是build时报错：
<details>
<summary>Gradle 日志</summary>
<pre><code>
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                       Gradle Plugin Repos                                        │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Gradle Central Plugin Repository                                                                 │
│ MavenRepo                                                                                        │
│ SpringRelease(https://repo.spring.io/release)                                                    │
│ ReleaseRepo(http://192.168.1.251:8081/nexus/content/repositories/releases/)                      │
│ SnapshotRepo(http://192.168.1.251:8081/nexus/content/repositories/snapshots/)                    │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                  Gradle Plugin Plugins Version                                   │
├─────────────────────────────────────────────────────────┬────────────────────────────────────────┤
│ ID                                                      │ Version                                │
├─────────────────────────────────────────────────────────┼────────────────────────────────────────┤
│ com.gradle.plugin-publish                               │ 1.0.0                                  │
└─────────────────────────────────────────────────────────┴────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                     Include Gradle Projects                                      │
├───────────────────────────────────────────┬──────────────────────────────────────────────────────┤
│ Path                                      │ Projects                                             │
├───────────────────────────────────────────┼──────────────────────────────────────────────────────┤
│ rest                                      │ cornucopia-rest                                      │
│ sdk                                       │ cornucopia-sdk                                       │
│ service                                   │ cornucopia-service                                   │
│ test                                      │ cornucopia-test                                      │
└───────────────────────────────────────────┴──────────────────────────────────────────────────────┘

> Configure project :
Build with IHub Plugins 1.2.10, You can see the documentation to learn more, See https://doc.ihub.pub/plugins.
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                       Gradle Project Repos                                       │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│ AliYunPublic(https://maven.aliyun.com/repository/public)                                         │
│ AliYunGoogle(https://maven.aliyun.com/repository/google)                                         │
│ AliYunSpring(https://maven.aliyun.com/repository/spring)                                         │
│ SpringRelease(https://repo.spring.io/release)                                                    │
│ ReleaseRepo(http://192.168.1.251:8081/nexus/content/repositories/releases/)                      │
│ SnapshotRepo(http://192.168.1.251:8081/nexus/content/repositories/snapshots/)                    │
│ MavenRepo                                                                                        │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
Using explicit version 1.0.1-SNAPSHOT
Unset git hooks path, learn more see https://doc.ihub.pub/plugins/#/iHubGitHooks
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                CORNUCOPIA Group Maven Bom Version                                │
├──────────────────────────────────┬───────────────────────────────┬───────────────────────────────┤
│ Group                            │ Module                        │ Version                       │
├──────────────────────────────────┼───────────────────────────────┼───────────────────────────────┤
│ pub.ihub.lib                     │ ihub-libs                     │ 1.0.12                        │
└──────────────────────────────────┴───────────────────────────────┴───────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                              CORNUCOPIA Group Maven Module Version                               │
├─────────────────────────────────┬───────────────────────────────────────┬────────────────────────┤
│ Group                           │ Module                                │ Version                │
├─────────────────────────────────┼───────────────────────────────────────┼────────────────────────┤
│ com.alibaba                     │ druid-spring-boot-starter             │ 1.2.11                 │
│ com.huaweicloud                 │ esdk-obs-java                         │ 3.22.3.1               │
│ de.flapdoodle.embed             │ de.flapdoodle.embed.mongo             │ 3.4.8                  │
└─────────────────────────────────┴───────────────────────────────────────┴────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                              CORNUCOPIA Group Maven Default Version                              │
├───────────────────────────────────────────────────────┬──────────────────────────────────────────┤
│ Group                                                 │ Version                                  │
├───────────────────────────────────────────────────────┼──────────────────────────────────────────┤
│ com.cheche365.common                                  │ 2.85.0                                   │
│ com.cheche365.test                                    │ 2.85.0                                   │
│ org.springdoc                                         │ 1.6.9                                    │
└───────────────────────────────────────────────────────┴──────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                 CORNUCOPIA Exclude Group Modules                                 │
├─────────────────────────────────────────────────────┬────────────────────────────────────────────┤
│ Group                                               │ Module                                     │
├─────────────────────────────────────────────────────┼────────────────────────────────────────────┤
│ com.athaydes                                        │ all                                        │
│ commons-logging                                     │ commons-logging                            │
│ log4j                                               │ log4j                                      │
│ org.apache.logging.log4j                            │ log4j-core                                 │
│ org.slf4j                                           │ slf4j-log4j12                              │
│ org.slf4j                                           │ slf4j-jcl                                  │
└─────────────────────────────────────────────────────┴────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                              CORNUCOPIA Config Default Dependencies                              │
├───────────────────────────────────────┬──────────────────────────────────────────────────────────┤
│ DependencyType                        │ Dependencies                                             │
├───────────────────────────────────────┼──────────────────────────────────────────────────────────┤
│ compileOnly                           │ cn.hutool:hutool-all                                     │
│ implementation                        │ org.codehaus.groovy:groovy-xml                           │
│ implementation                        │ org.codehaus.groovy:groovy-dateutil                      │
│ implementation                        │ org.codehaus.groovy:groovy-templates                     │
│ implementation                        │ org.codehaus.groovy:groovy-nio                           │
│ implementation                        │ org.codehaus.groovy:groovy                               │
│ implementation                        │ org.slf4j:slf4j-api                                      │
│ implementation                        │ org.codehaus.groovy:groovy-json                          │
│ implementation                        │ org.codehaus.groovy:groovy-groovydoc                     │
│ implementation                        │ org.codehaus.groovy:groovy-sql                           │
│ implementation                        │ org.codehaus.groovy:groovy-datetime                      │
│ testImplementation                    │ org.spockframework:spock-spring                          │
│ testRuntimeOnly                       │ com.athaydes:spock-reports                               │
│ pmd                                   │ com.alibaba.p3c:p3c-pmd                                  │
│ runtimeOnly                           │ org.slf4j:jul-to-slf4j                                   │
│ runtimeOnly                           │ org.slf4j:log4j-over-slf4j                               │
└───────────────────────────────────────┴──────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                          CORNUCOPIA Config Default Require Capabilities                          │
├─────────────────────────────────────────────────────┬────────────────────────────────────────────┤
│ Dependency                                          │ Capabilities                               │
├─────────────────────────────────────────────────────┼────────────────────────────────────────────┤
│ pub.ihub.lib:ihub-groovy                            │ groovy4-support                            │
└─────────────────────────────────────────────────────┴────────────────────────────────────────────┘

> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Errors occurred while build effective model from C:\Users\Huabin\.gradle\caches\modules-2\files-2.1\com.alibaba\druid\1.2.11\7a2e5cad15e457ab8d36d01a442d1aac667fd560\druid-1.2.11.pom:
	'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-tools.jar in com.alibaba:druid:1.2.11
	'dependencies.dependency.systemPath' for com.sun:jconsole:jar must specify an absolute path but is ${project.basedir}/lib/openjdk-1.8-jconsole.jar in com.alibaba:druid:1.2.11
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime
Could not resolve: org.codehaus.groovy:groovy-xml
Could not resolve: org.codehaus.groovy:groovy-templates
Could not resolve: org.codehaus.groovy:groovy-nio
Could not resolve: org.codehaus.groovy:groovy
Could not resolve: org.codehaus.groovy:groovy-json
Could not resolve: org.codehaus.groovy:groovy-groovydoc
Could not resolve: org.codehaus.groovy:groovy-sql
Could not resolve: org.codehaus.groovy:groovy-datetime

BUILD SUCCESSFUL in 2s
</code></pre>
</details>

你啥时候有空，帮我看看。
我看**projectReport**导出的依赖，确实在各个子项目上都有codehaus旧groovy组的依赖，但是不知道是在哪儿加的。
我怀疑是`ihub-groovy`插件添加的旧依赖，当然也有可能是某个开关设置不正确导致的。

多谢。

### 预期行为

无错误地构建成功。

### 实际行为

试图Resolve Groovy 3相关依赖。

### Java版本

Java17

### Gradle版本

Gradle 7.5

### 系统环境

Windows

**Comment by zhanghuabin** [comment]
这是其中一个子项目的编译依赖，既有`org.apache`也有`org.codehaus`：

![projectReport截图](https://user-images.githubusercontent.com/5813426/188809972-328aa388-2ada-4e55-8b2e-60a9d8cc8d0a.png)

**Comment by henry-hub** [comment]
groovy3和groovy4的依赖控制不适用这种方式，还是需要使用开关控制
```properties
iHub.enableGroovy4=true
```
https://github.com/ihub-pub/plugins/pull/299#issuecomment-1217381496

**Comment by zhanghuabin** [comment]
下面这个这是我跑所有测试用例的**IntelliJ Idea Run Configuration**：

[test-all.xml](https://pastebin.com/kuEW9tu9)

**Comment by zhanghuabin** [comment]
在经过一系列折腾后，测试用例全部跑通了。

以下是关键修改：

* 要使用`iHub.enableGroovy4`属性开关， #299 中所述方法的适用场景与此问题不大相同
* Spock测试框架版本要显式指定Groovy4版本（但不知为何不能通过`org.spockframework,version`属性来指定）

以上。

请关闭此Issue，多谢。

**Comment by henry-hub** [comment]
> 在经过一系列折腾后，测试用例全部跑通了。
> 
> 以下是关键修改：
> 
> * 要使用`iHub.enableGroovy4`属性开关， [feat(groovy): 添加“是否启用Groovy 4”的开关 #299](https://github.com/ihub-pub/plugins/pull/299) 中所述方法的适用场景与此问题不大相同
> * Spock测试框架版本要显式指定Groovy4版本（但不知为何不能通过`org.spockframework,version`属性来指定）
> 
> 以上。
> 
> 请关闭此Issue，多谢。

- groovy3与groovy4依赖不适用于[feat(groovy): 添加“是否启用Groovy 4”的开关 #299](https://github.com/ihub-pub/plugins/pull/299) 中所述场景，还是要通过开关切换
- 最开始的通过插件管理组件版本时支持这样的方式（`org.spockframework.version`）来指定，后续组件版本统一通过[bom组件](https://mvnrepository.com/artifact/pub.ihub.lib/ihub-libs)来管理默认版本，如果需要其他版本可以通过[bom插件](https://doc.ihub.pub/plugins/#/iHubBom?id=%e9%85%8d%e7%bd%ae%e7%a4%ba%e4%be%8b)指定，相关组件的默认版本会在后续版本升级 https://github.com/ihub-pub/libs/pull/215
感谢建议与反馈
