### ISSUE TITLE
【需求】添加Jacoco Console Report

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#38]
### 背景描述

Gradle的Jacoco插件默认仅提供三种报告，分别是XML、CSV和HTML。

而GitLab CICD过程中可以通过解析控制台输出的信息，得到各种类型语言的项目的测试覆盖率，然后通过特定URL显示在README中。

### 解决方案

参考最新的 **cornucopia**、 **ihub-plugin** 分支，其中的`verification_settings.gradle`中添加了一段代码。

这段代码可以打印每一个项目测试后的覆盖率报告。尽管有用，但是我们还是需要一个 **总覆盖率** 来提供CICD所用。

所以，这段代码的启发在于以下几点：

* 可以得到各个项目各自的、分项的覆盖率

* 各个项目的覆盖率是否可以集中保存

  这需要仔细研究一下Gradle执行任务的机制，看看有没有提供类似如下特征的机制：

  * 能钩住在各个项目上运行的、关注的任务

    用于记录各项目的分项覆盖率。
 
  * 能钩住整体的生命循环关键节点

    如此才有机会计算 **总覆盖率**。
 
  * 能声明全局的、跨任务、跨项目的变量

    如果想透过static成员的思路来实现，那么必须考虑Gradle Daemon为true时的场景。

* 总覆盖率的计算规则

  尽管我们最为关心分支覆盖率，那么直观做法就是把各个项目的分支覆盖率简单平均，从而得到 **总覆盖率**。

  但是，上述其实是 *分支总覆盖率*，如果再彻底一点：首先将各项目的分项覆盖率简单平均，然后将各项目的简单平均值再做简单平均，得到另一种 **总覆盖率**。

  上述两种计算方法仅是抛砖引玉，无论使用何种计算方式，最后输出的文本必须用容易被解析的特殊格式输出到控制台。

本需求可能需要比较长时间的思考、验证，可以作为一个重要但不优先的任务。

另外，在`settings.gradle`中，我添加了两个有类似能力的插件，但是被注释掉了，因为他们不兼容最新版本的Gradle，其中有一个插件比较活跃，可能会在短期内推出新版。

但是它们估计都只能打印分项覆盖率，而不能统计 **总覆盖率** ，这个功能是本插件可以突破的亮点。

**Comment by henry-hub** [comment]
可以实现，主要确认好统计规则就行，我研究一下
