### ISSUE TITLE
改造pub-apps/cornucopia时遇到的几个问题

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#5]
项目分支：`ihub-plugin`

* **IntelliJ IDEA** 刷新项目暂时没问题了，代价是
  * 插件 **pub.ihub.plugin.ihub-groovy** 不能用，暂时恢复引用`groovy_settings.gradle`和`groovy_essential_deps.gradle`作为替代方案
  * **rest** 项目不能写`apply { plugin '...ihub-native' }`，否则报`IHubVerificationPlugin`的问题，以为是`ihub-native`的问题，但其实是 **CodeNarc** 配置找不到，照着代码的要求添加目录和文件后就可以了，但是错误提示可以改得再友好一些
* 执行`gradlew classes`时报错
  * 总是试图从`https://maven.pkg.github.com/ihub-pub`这个需要授权的repo去解析公司组件 **Pom** 信息，所以必定`401`失败，建议参考`default_deps.gradle`的 **14~34** 行配置，修复`IHubPluginsPlugin`中的相关问题

**Comment by zhanghuabin** [comment]
经测试，1.0.1解决了Groovy插件问题。

**Comment by henry-hub** [comment]
感谢反馈👍
