### ISSUE TITLE
Lombok @Data Improve your Code Coverage

### ISSUE THREAD

**Issue by shan-xf** [ihub-pub/plugins#56]
On my previous project we had a problem to achieve good code coverage with Jacoco. Lombok was used extensively on the project and each time we added new domain object we were loosing those precious code coverage percentages.

**Comment by henry-hub** [comment]
lombok有两种使用方式，依赖`org.projectlombok:lombok`组件和使用`io.freefair.lombok`插件，改用插件可以解决以上问题
