### ISSUE TITLE
改进建议：把getProjectVersion()机制也做进插件

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#6]
如题，将原先`versioning_settings.gradle`中的内容也做进插件。

**Comment by henry-hub** [comment]
本次1.0.2版本并未复刻之前**versioning_settings.gradle**的**getProjectVersion()**方法，只是做了一些版本管理扩展，原因如下：
- 之前的方法会将应用版本与组件版本绑定，但实际组件版本与应用版本该是独立的
- 这套插件目前提供了多种组件版本管理方式，建议应用版本与组件版本分开管理
pub-apps/cornucopia改进建议如下：
- 应用版本可以通过**git-version**获取仓库tag版本，无须本地维护版本，通过tag维护即可，也可通过**version**属性管理
- 组件版本可以通过**iHubBom**插件扩展进行统一配置，配置方式有：导入bom、单独指定依赖版本、强制组版本，详见**multi**示例
- 建议可以有一个专门的bom组件统一管理组件版本

示例如下（移除所有的${getProjectVersion(cheche365_version)}）：
![image](https://user-images.githubusercontent.com/23556146/116786820-5ffa6980-aad3-11eb-82a7-2aef38cf7dbc.png)
