### ISSUE TITLE
🐛 iHubBom/dependencyVersions配置对个别module无法指定版本

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#625]
### 受影响的软件包和版本

iHub Plugin 1.3.4~1.4.0

### 复现步骤

**Gradle 8.3** + **Java 17**

这个问题目前只发生在`com.athaydes:spock-reports`这个模块上。

如果用下面这个写法，版本始终都是`2.5.0-groovy-4.0`，而非`2.5.1`。

```
iHubBom {
    dependencyVersions {
        group 'com.athaydes'            modules 'spock-reports'             version ‘2.5.1-groovy-4.0’
    }
}
```

但如果改换为下面的写法，就可以指定为`2.5.1`。

```
iHubBom {
    groupVersions {
        group 'com.athaydes'            version ‘2.5.1-groovy-4.0’
    }
}

```

另外，如果不自行指定版本，该模块的版本也是`2.5.0`。

### 预期行为

无论版本指定到模块级还是组级，都应该为`2.5.1`。

而且对于不做任何版本指定的情况，貌似也应该是`2.5.1`，因为我看了一下最新的`ihub-pub/libs`项目代码，其`libs.versions.toml`中声明的版本就是`2.5.1`。

唯一一个声明了`2.5.0`版本的位置是`ihub-base-test/src/main/resources/libs.versions.toml`，但它不应该会影响解决版本的行为。

所以这个`2.5.0`从何而来的，很奇怪。

在`iHubBom/dependencyVersions`配置中对其他组件指定版本的行为是符合预期的，比如`com.huaweicloud:esdk-obs-java`。

### 实际行为

略。

### Java版本

Java17

### Gradle版本

其他（请在复现步骤说明版本）

### 系统环境

Windows

**Comment by henry-hub** [comment]
`dependencyVersions`配置之所以不生效，是因为有其他的插件使用`配置策略规则`的方式（即`groupVersions`的配置方式）指定了`com.athaydes:spock-reports`的版本为`2.5.0-groovy-4.0`，通过查看依赖树可以看出来：
![image](https://github.com/ihub-pub/plugins/assets/23556146/c207092a-b7df-437e-8f43-34bf94c56ee4)
这个问题我之前也发现了，只能通过`groupVersions`的方式去强制覆盖版本，`ihub-plugins`使用的groovy版本是3.0，目前也是使用`groupVersions`的方式配置的。
另外，`ihub-libs`最后发布的版本对应`com.athaydes:spock-reports`版本还是`2.5.0-groovy-4.0`，代码里是发版之后才升级到`2.5.1-groovy-4.0`。

**Comment by henry-hub** [comment]
以上排查并未发现有其他组件明确通过版本策略的方式强制覆盖`com.athaydes:spock-reports`版本，经过再次排查发现是由于`ihub-test`插件添加`com.athaydes:spock-reports`组件时改用ihub-libs组件别名导致，**组件别名里设定了版本号**，`springDependencyManagement`的版本管理策略**不会强制覆盖已有版本，组件没有版本号才会为其添加版本号**，具体修复内容见 #636
