### ISSUE TITLE
改进建议：要求默认include的子项目目录中必须包含build.gradle

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#7]
没有这个限制就会随着项目变动，时不时蹦出一个明显不是Gradle项目的目录被include进来，比如node_modules，现在只能通过手动维护skipped_dirs属性来显式排除，有点麻烦。

![image](https://user-images.githubusercontent.com/5813426/116533028-7f4a9880-a913-11eb-87a7-50417191b256.png)

**Comment by henry-hub** [comment]
- 多子项目本身就是需要维护项目目录的，正向选择项目或者通过skipped_dirs反选，skipped_dirs属性本就是用来排除如node_modules以及不需要加入的目录的
- 由于插件是支持单项目，所以也不会默认导入子项目，不过**可以在导入项目的时候做一些过滤，排除一些常见的非项目目录**

**Comment by zhanghuabin** [comment]
> * 多子项目本身就是需要维护项目目录的，正向选择项目或者通过skipped_dirs反选，skipped_dirs属性本就是用来排除如node_modules以及不需要加入的目录的
> * 由于插件是支持单项目，所以也不会默认导入子项目，不过**可以在导入项目的时候做一些过滤，排除一些常见的非项目目录**

第一点，需要修正include和skipped_dirs之间的冲突问题，让用户二选一：用include，就别用skipped_dirs，反之。一旦都用，直接就提示错误。
我稍后在settings里改为使用includeProjects，并去除skipped_dirs属性配置。
